### ISSUE TITLE
Multi select field issue

### ISSUE THREAD

**Issue by LukaszKopyszko** [ihslimn/jet-form-builder-update-field#4]
Hi!
First of all, I would like to appreciate your work. 

I currently have a setup, where in first multi select field i am listing terms of my CPT like this: 

![1](https://github.com/ihslimn/jet-form-builder-update-field/assets/46007010/25b5d6b7-e1fd-4f36-91b9-3509b09557c6)

And i want to retrieve list of posts in second multi select input, based on chosen terms from first one: 

![image](https://github.com/ihslimn/jet-form-builder-update-field/assets/46007010/4e71bb10-1c22-4b96-934f-ae26e5f92d43)

Works fine with single selects, but it keeps displaying all posts without filtration in second multi select when it is MULTI SELECT ENABLED. 

This is my jet engine query, really simple: 

![image](https://github.com/ihslimn/jet-form-builder-update-field/assets/46007010/64519768-31dd-44cf-ae50-29e01ad5544f)

![image](https://github.com/ihslimn/jet-form-builder-update-field/assets/46007010/e9c24915-5675-478f-89b1-c60d97abce9b)

![image](https://github.com/ihslimn/jet-form-builder-update-field/assets/46007010/dcecbd30-59dd-471d-8bff-fb3aebf92fc1)

Of course, i have updater selected: 

![image](https://github.com/ihslimn/jet-form-builder-update-field/assets/46007010/1cdb3dda-c51d-46a1-957b-0020924a7389)

Is this something not implemented in plugin, or just my setup isn't good? 

Will be glad to hear from you!

**Comment by LukaszKopyszko** [comment]
Now it works, what would be another good fix is that when you have some options selected in first multi, when you are adding some, it should not delete chosen options from second field. It should just adding new options to select. But if you are deleting parent of something related in second it should of course delete this also.

**Comment by ihslimn** [comment]
this is an interesting idea; however, not sure when it might be implemented
will consider adding this feature in the future
