### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by JuanCar29** [ihslimn/jet-form-builder-update-field#5]
I have this error despite the data update working fine.
web https://mitienda.instawp.xyz/
![Captura de pantalla 2024-01-17 154119](https://github.com/ihslimn/jet-form-builder-update-field/assets/90837626/5969c34b-4726-46b3-a098-8c2c0d5dc938)
[formulario-de-entradas-de-usuarios.json](https://github.com/ihslimn/jet-form-builder-update-field/files/13964627/formulario-de-entradas-de-usuarios.json)

**Comment by ihslimn** [comment]
as for now you may just turn off debug so that the notice will not be shown
the next version will include the fix

**Comment by JuanCar29** [comment]
I have modified these lines of the plugin and it no longer gives me the error and it continues to work fine. But I don't know if it's well done. Thank you very much for the plugin, it is fantastic.

		if ( ! empty( $attrs['jfb_update_fields_field_to_listen'] ) || ! $attrs['jfb_update_fields_update_on_button'] ) {
			$block->add_attribute( 'data-update-listen-to', $attrs['jfb_update_fields_field_to_listen'] );
		}

		if ( ! empty( $attrs['jfb_update_fields_button_name'] )  ) {
			$block->add_attribute( 'data-update-on-button', $attrs['jfb_update_fields_button_name'] );
		}

**Comment by ihslimn** [comment]
yes, you are right
I just forgot to add checks for existence of array elements
