### ISSUE TITLE
listing updater

### ISSUE THREAD

**Issue by JuanCar29** [ihslimn/jet-form-builder-update-field#6]
The listing updater block, I don't see how it can be used. Is there any example?
![Captura de pantalla 2024-01-28 115559](https://github.com/ihslimn/jet-form-builder-update-field/assets/90837626/8caf0d5c-69a6-4bd1-844d-e9ca42d5bfac)

**Comment by ihslimn** [comment]
hi!
for now it does nothing :)
actually it got included by mistake
I planned to make it so that the listing grid contents may be updated based on field value, but got no time to implement it correctly
so it's just stuck for now, will remove it not to confuse people

**Comment by JuanCar29** [comment]
Thank you very much for the clarification. For the purposes of the plugin it works perfectly and has been very useful to me.
