### ISSUE TITLE
update on action button 

### ISSUE THREAD

**Issue by edmundspriede** [ihslimn/jet-form-builder-update-field#7]
hi, i had this working 5 min ago, but now i cannot get update on action button.

refresh button should update text field. i saw api call when it was working, but now api is not called

https://esimgo.m50.lv/test/

![update test](https://github.com/ihslimn/jet-form-builder-update-field/assets/5557888/ae04c452-99cd-40d1-8018-22ad33f64522)

**Comment by edmundspriede** [comment]
i am trying everything, but button update is not working. as it is not in docs i suppose it is not ready yet?

**Comment by ihslimn** [comment]
Update Button got broken after one of JetFormBuilder updates (API slightly changed)
will fix it in the future

**Comment by ihslimn** [comment]
You can still add the button by copying it from existing form

**Comment by edmundspriede** [comment]
ok , i just wanted to update a field on submit action, after i read data from external API. i think is it nice feature.

**Comment by ihslimn** [comment]
well it never worked as you describe - updating a field value after the form submit
it could only use query/callback function to set field value

anyway, will fix it - hopefully soon

**Comment by ihslimn** [comment]
fixed in https://github.com/ihslimn/jet-form-builder-update-field/commit/7815ae7df0917f8322ff8e67358072def79ff860
