### ISSUE TITLE
Update fields dont work

### ISSUE THREAD

**Issue by sea4all-g** [ihslimn/jet-form-builder-update-field#9]
Hi there,
 i have updated croco plugins and after that update fields do not work. i got an erro in my console log 
" Uncaught TypeError: 
wp.apiFetch is not a function
    at updateFormField  "

Could you please check it ?
thanks

**Comment by xbric** [comment]
I have the same problem : Field Updater does not work anymore since what I believe to be a recent JetEngine update (but not 100% sure). I get the same "Uncaught TypeError: wp.apiFetch is not a function" on my console log.

**Comment by sea4all-g** [comment]
Hi there, 
i found the solution....put this code via code snippet or in the functions.php and the error will disappear.
`function my_custom_enqueue_scripts() {
    // Enqueue wp-api-fetch
    wp_enqueue_script('wp-api-fetch');

    // Enqueue your custom script with wp-api-fetch as a dependency
    wp_enqueue_script('my-custom-script', get_template_directory_uri() . '/js/my-custom-script.js', array('wp-api-fetch'), '1.0', true);
}
add_action('wp_enqueue_scripts', 'my_custom_enqueue_scripts');
add_action('admin_enqueue_scripts', 'my_custom_enqueue_scripts'); // If needed `

**Comment by xbric** [comment]
Thanks.  Your code solved the problem 👍 .

**Comment by ihslimn** [comment]
will add wp fetch to script dependencies as soon as possible

**Comment by ihslimn** [comment]
fixed in https://github.com/ihslimn/jet-form-builder-update-field/commit/59c485f8762139a6b301d465ed38a60c70867c3f

**Comment by sea4all-g** [comment]
Thanks a lot ! we just remove the old files and upload the new zip?

**Comment by ihslimn** [comment]
yes, you may delete and upload a new one
